apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-example-app
  template:
    metadata:
      labels:
        app: argocd-example-app
    spec:
      containers:
      - name: argocd-example-app
        image: liquidreply/argocd-example-app:1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000" # Cambiar al puerto deseado
