apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  type: NodePort
  selector:
    app: argocd-example-app
  ports:
    - protocol: TCP
      port: 3000       # Puerto expuesto externamente
      targetPort: 80   # Puerto dentro del contenedor
